def help():
    if mode == "admin":
        print("========================HELP========================")
        print("register         - untuk melakukan registrasi user baru")
        print("carirarity       - untuk melakukan pencarian gadget berdasarkan rarity")
        print("caritahun        - untuk melakukan pencarian gadget berdasarkan tahun")
        print("tambahitem       - untuk melakukan penambahan item ke dalam inventory")
        print("hapusitem        - untuk melakukan penghapusan item pada database")
        print("ubahjumlah       - untuk melakukan perubahan jumlah gadget dan consumable")
        print("riwayatpinjam    - untuk melihat riwayat peminjaman gadget")
        print("riwayatkembali   - untuk melihat riwayat pengembalian gadget")
        print("riwayatambil     - untuk melihat riwayat pengebalian consumable")
        print("save             - untuk melakukan penyimpanan data ke dalam file")
        print("help             - untuk memberikan panduan penggunaan sistem")
        print("exit             - untuk keluar dari aplikasi")
    elif mode == "pengguna":
        print("========================HELP========================")
        print("carirarity       - untuk melakukan pencarian gadget berdasarkan rarity")
        print("caritahun        - untuk melakukan pencarian gadget berdasarkan tahun")
        print("pinjam           - untuk melakukan peminjaman gadget")
        print("kembalikan       - untuk melakukan pengembalian gadget secara seutuhnya")
        print("minta            - untuk melakukan permintaan consumable yang tersedia")
        print("save             - untuk melakukan penyimpanan data ke dalam file")
        print("help             - untuk memberikan panduan penggunaan sistem")
        print("exit             - untuk keluar dari aplikasi")
